# Generated by Django 5.2.4 on 2025-08-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=11)),
                ('instagram', models.CharField(max_length=25)),
                ('by', models.CharField(max_length=25)),
                ('motivo', models.CharField(max_length=100)),
            ],
        ),
    ]
